name: HTML CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up a simple build step
        run: echo "Build step for HTML project"

      - name: Deploy to AWS EC2
        run: |
          echo "$EC2_SSH_KEY" > private_key.pem
          chmod 600 private_key.pem
          ssh -i private_key.pem -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST 'sudo rm -rf /var/www/html/devops-html-app/*'
          scp -i private_key.pem -o StrictHostKeyChecking=no index.html $EC2_USER@$EC2_HOST:/var/www/html/devop-html-app/
        env:
          EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
          EC2_USER: ${{ secrets.EC2_USER }}
          EC2_HOST: ${{ secrets.EC2_HOST }}
          # Commands to deploy to EC2 will be added here
          
