name: Deploy to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup SSH
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key.pem
          chmod 600 private_key.pem
          ssh-keyscan -H 13.201.134.155 >> ~/.ssh/known_hosts

      - name: Deploy files to EC2
        run: |
          scp -i private_key.pem -o StrictHostKeyChecking=no index.html ssh -i "html-app.pem" ec2-user@ec2-13-201-134-155.ap-south-1.compute.amazonaws.com:/var/www/html/

      - name: Cleanup SSH Key
        run: rm private_key.pem
